$script_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server-5.7 && \
  mysql -e "create user 'devuser'@'%' identified by 'senha';"
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"
  config.vm.provider "virtualbox" do |vb|
  vb.memory = 512
  vb.cpus = 1
end

  config.vm.define "VMansible" do |ansible|
    ansible.vm.network "private_network",ip: "192.168.100.44",

    ansible.vm.provision "shell",
         inline: "apt-get update && \
                  apt-get install -y software-properties-common && \
                  add-apt-repository --yes --update ppa:ansible/ansible && \
                  apt-get install -y ansible"

    ansible.vm.provision "shell",
        inline: "cp /vagrant/id_bionic /home/vagrant/ && \
                chmod 600 /home/vagrant/id_bionic && \
                sudo chown vagrant:vagrant id_bionic"

    ansible.vm.provision "shell",
        inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
                /vagrant/configs/ansible/playbook.yml"
  end

  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network",
      ip: "192.168.100.43",bridge: "Realtek PCIe GbE Family Controller #2"

    mysqlserver.vm.provision "shell",
      inline: "cat /vagrant/configs/id_bionic.pub >> .ssh/authorized_keys"
  end

end
