$script_mysql = <<-SCRIPT
  apt-get update && \
  apt-get install -y mysql-server-5.7 && \
  mysql -e "create user 'devuser'@'%' identified by 'senha';"
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"
  config.vm.provider "virtualbox" do |vb|
  vb.memory = 512
  vb.cpus = 1
end

  # config.vm.define "mysqldb" do |mysql|
  #         mysql.vm.network "public_network",
  #           ip: "192.168.100.41",bridge: "Realtek PCIe GbE Family Controller #2"
  #
  #         mysql.vm.provision "shell",
  #           inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
  #         mysql.vm.provision "shell", inline: $script_mysql
  #         mysql.vm.provision "shell",
  #           inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
  #         mysql.vm.provision "shell",inline: "service mysql restart"
  #
  #         mysql.vm.synced_folder "./configs", "/configs"
  #         mysql.vm.synced_folder ".", "/vagrant", disabled: true
  # end

  config.vm.define "devweb" do |devweb|
         devweb.vm.network "forwarded_port", guest: 8888, host: 9091
         devweb.vm.network "public_network",
            ip: "192.168.100.42",bridge: "Realtek PCIe GbE Family Controller #2"

         devweb.vm.provision "shell",
            inline: "sudo apt-get update && apt-get install -y puppet"

         devweb.vm.provision "puppet" do |puppet|
           puppet.manifests_path = "./configs/manifests"
           puppet.manifest_file = "devweb.pp"
         end
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network",
      ip: "192.168.100.44",bridge: "Realtek PCIe GbE Family Controller #2"

    ansible.vm.provision "shell",
         inline: "apt-get update && \
                  apt-get install -y software-properties-common && \
                  add-apt-repository --yes --update ppa:ansible/ansible && \
                  apt-get install -y ansible"

    ansible.vm.provision "shell",
        inline: "cp /vagrant/id_bionic /home/vagrant/ && \
                chmod 600 /home/vagrant/id_bionic && \
                sudo chown vagrant:vagrant id_bionic"

    ansible.vm.provision "shell",
        inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
                /vagrant/configs/ansible/playbook.yml"

  end

  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network",
      ip: "192.168.100.43",bridge: "Realtek PCIe GbE Family Controller #2"

    mysqlserver.vm.provision "shell",
      inline: "cat /vagrant/configs/id_bionic.pub >> .ssh/authorized_keys"
  end

end
